GET http://localhost:3000/places?text=tucurui, pa

###
GET http://localhost:3000/places?text=breu branco, pa

###

@originId = ChIJ4bpmJiSNv5IRoWk01iHKBvs

@destinationId = ChIJAb9uB-SOv5IR8eAaD-0KOYY

###
GET http://localhost:3000/directions?originId={{ originId }}&destinationId={{ destinationId }}

###
POST http://localhost:3000/routes
Content-Type: application/json

{
    "name": "Rota 1",
    "origin_id": "{{ originId }}",
    "destination_id": "{{ destinationId }}"
}

### 
GET http://localhost:3000/routes

###
GET http://localhost:3000/routes/675759eb2b3db1245872cdee