@baseUrl = http://localhost:3000

GET {{ baseUrl }}/places?text=tucurui, pa

###
GET {{ baseUrl }}/places?text=goianesia, pa

###

@originId = ChIJ4bpmJiSNv5IRoWk01iHKBvs

@destinationId = ChIJtd33HDiewJIRmUBy7E1kjTQ

###
GET {{ baseUrl }}/directions?originId={{ originId }}&destinationId={{ destinationId }}

###
POST {{ baseUrl }}/routes
Content-Type: application/json

{
    "name": "Tucuruí - Goiânesia",
    "origin_id": "{{ originId }}",
    "destination_id": "{{ destinationId }}"
}

###
POST {{ baseUrl }}/routes/675d88f1bd7c08a50c93f065/start

### 
GET {{ baseUrl }}/routes

###
GET {{ baseUrl }}/routes/675a072f06d5e00147f90f11